server:
  port: 8070
spring:
  datasource:
    password: 12345
    url: jdbc:mysql://localhost:3306/electronic_store?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
  mail:
    host: smtp.gmail.com
    password: wthgsmipsxsssccq
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: kichhoattktest@gmail.com
  security:
    oauth2:
      client:
        registration:

javaweb:
  app:
    jwtSecret: =======================BezKoder=Spring===========================
    jwtExpirationMs: 86400000